apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: many-apps-application-set
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/codefresh-contrib/gitops-cert-level-2-examples.git
      revision: HEAD
      directories:
      - path: application-sets/example-apps/*
  template:      
    metadata:
      name: '{{path.basename}}'
    spec:
      # The project the application belongs to.
      project: default
